### ISSUE TITLE
Fails to load due to requiring currentRoom model.

### ISSUE THREAD

**Issue by itotallyrock** [extplug/ExtPlug#33]
When launching from the bookmarklet the console displays

```
Uncaught Error: Script error for: plug/models/currentRoom
```

And after that message is displayed nothing else happens.

**Comment by itotallyrock** [comment]
It does this because it doesn't know where to find it.

With this error
`GET https://plug.dj/_/static/js/plug/models/currentRoom.js`

I'm assuming this is due to the plug-module class not declaring it into global namespace correctly and require assumes it is a path since it isn't defined and fails to retrieve it.

**Comment by itotallyrock** [comment]
I've found out from personal usage that this doesn't occur when using the user script.  Which may help to narrow it down to only areas that have something different from the bookmarklet.

**Comment by goto-bus-stop** [comment]
Thanks for the report! It looks like plug-modules isn't finding the current room model when ExtPlug is loaded late (i.e. loaded after you've fully joined a room), which is why it works with the userscript but not with the bookmarklet.

I'll publish an ExtPlug version using the fixed plug-modules in a minute.
